### ISSUE TITLE
Error on gvim windows

### ISSUE THREAD

**Issue by giahuyng98** [vim-erlang/vim-erlang-omnicomplete#26]
error when hit C-X C-O on gvim windows:

```
Error detected while processing function erlang_complete#Complete[22]..<SNR>27_ErlangFindExternalFunc:
line   18:
E484: Can't open file C:\Users\mine\AppData\Local\Temp\VIo677A.tmp
Press ENTER or type command to continue
```

**Comment by hcs42** [comment]
Could you try the following scenarios:

1.  Open an empty Erlang file in GVim and type C-x C-o. Do you get the error? If not, what happens?

2.  Type `lists:m` and type C-x C-o. Do you get the error? If not, what happens?

3.  Run the following command in GVim (replace the `...` with your path):

    ```
    :echo system ('escript /.../vim-erlang-omnicomplete/autoload/erlang_complete.erl list-modules') 
    ```

    Does Vim start printing a long list (you can hit `q` to stop it), or do you get the error?

**Comment by giahuyng98** [comment]
1. ```
Error detected while processing C:\Program Files (x86)\Vim\vim81\plugin\vim-erlang-omnicomplete-master\autoload\erlang_c
omplete.vim:
line   18:
E122: Function <SNR>26_starts_with already exists, add ! to replace it
line   83:
E122: Function <SNR>26_get_preview_line already exists, add ! to replace it
line  135:
E122: Function erlang_complete#Complete already exists, add ! to replace it
line  148:
E122: Function <SNR>26_ErlangFindNextNonBlank already exists, add ! to replace it
line  219:
E122: Function <SNR>26_ErlangFindExternalFunc already exists, add ! to replace it
line  286:
E122: Function <SNR>26_ErlangFindLocalFunc already exists, add ! to replace it
line  290:
E122: Function erlang_complete#ClearAllCache already exists, add ! to replace it
line  296:
```

2. ```
Error detected while processing function erlang_complete#Complete[22]..<SNR>26_ErlangFindExternalFunc:
line   18:
E484: Can't open file C:\Users\mine\AppData\Local\Temp\VIoD7B3.tmp
```

3.
`E484: Can't open file C:\Users\mine\AppData\Local\Temp\VIo981B.tmp`

**Comment by hcs42** [comment]
I found a few similar error reports in Vim plugins and some other information about this issue:

- https://vim.fandom.com/wiki/Execute_external_programs_asynchronously_under_Windows#Some_notes_on_cmd.exe_quoting
- http://vimdoc.sourceforge.net/htmldoc/options.html#'shellxquote'
- https://github.com/mattn/gist-vim/issues/48#issuecomment-12916349
- https://github.com/mattn/gist-vim/issues/48#issuecomment-259697627
- https://github.com/google/vim-codefmt/issues/86

Based on these:

1.  What is the output of the following command?

    ```vim
    :set shellcmdflag? shellquote? shellxquote?
    ```

    Can you try:

    ```vim
    :set shellxquote=\"
    ```

    And see if the error still occurs. If yes, then could you also try the following:

    ```vim
    :set shell=cmd
    :set shellcmdflag=/c
    ```

2. What is your Vim version? See https://groups.google.com/forum/#!topic/vim_dev/CNIODLeIt54 for a similar error caused by a Vim bug. If this is the problem then it can be fixed with installing the newest Vim version.

**Comment by giahuyng98** [comment]
`:set shellxquote=\"
`
solves the problem.
Thanks

**Comment by giahuyng98** [comment]
`:set shellxquote=\"
`
solves the problem.
Thanks

**Comment by MartyLake** [comment]
For the next internet people who lands there, I randomly arrived here from google searches about ctags that would not work because C:\Users\mine\AppData\Local\Temp\ was not accessible.

```
:set shellxquote=\"
:set shell=cmd
:set shellcmdflag=/c
```
solved my problem
