### ISSUE TITLE
Completion Error when completing exported module functions

### ISSUE THREAD

**Issue by BrettHemes** [vim-erlang/vim-erlang-omnicomplete#28]
When completing exported functions of modules, the following error happens:

      1 /home/hemes/.vim/bundle/vim-erlang-omnicomplete/autoload/erlang_complete.erl:885:14: Warning: filename:find_src/1 is removed; use filelib:find_source/1,3 instead                    
      2 %  885|         case filename:find_src(Mod) of                                                       
      3 %     |              ^                                                                               
      4    

Simply changing `filename:find_src` to `filelib:find_source` as suggested works and solves the issue.

**Comment by hcs42** [comment]
Thank you, I will fix this.

The older Erlang versions contained `filename:find_src`. The `filelib:find_source` function was added in Erlang 20 as a replacement. Simply using the new function would have caused the plugin not to work with old Erlang versions. ([See this comment.](https://github.com/vim-erlang/vim-erlang-omnicomplete/blob/924a50ed0ad93141063d0f27c9f62b1bea991baf/autoload/erlang_complete.erl#L10-L13))

In any case, `filename:find_src` function was removed from Erlang 24, so it's time to fix it properly so that the plugin uses the library function available in the Erlang installation.

**Comment by hcs42** [comment]
@BrettHemes 

I pushed a commit to my [`issue_28`](https://github.com/hcs42/vim-erlang-omnicomplete/commits/issue_28) branch which contains a fix for the issue.

I have executed the automatic tests on it but I haven't tried it on a real project yet. The commit message also needs some explanation.

I decided however to push it so that you can try it (instead of pushing a more polished version only later).

**Comment by BrettHemes** [comment]
Yup, this one works too.

**Comment by hcs42** [comment]
Thank you. The fix is now available in the master branch too.
