### ISSUE TITLE
It is best to pop up a menu after entering a colon

### ISSUE THREAD

**Issue by LuoYou1989** [vim-erlang/vim-erlang-omnicomplete#29]

**Comment by hcs42** [comment]
Could you elaborate on your suggestion?

In Vim, if you want to get omnicompletion, you type your text (e.g., `lists:`), and then you hit Ctrl+x Ctrl-o to get the completion popup. See e.g. https://vimhelp.org/insert.txt.html#compl-omni.

**Comment by sanmiguel** [comment]
There are also generic extensions such as https://github.com/ervandew/supertab that extend omnicomplete to activate on `<Tab>`. This may feel more familiar if you are used to IDEs.

**Comment by hcs42** [comment]
@sanmiguel Thank you.

If the request is indeed showing the omnicompletion menu every time the user types a colon, that it outside the scope of this plugin.

However, the user can achieve that with a mapping (e.g., `:inoremap <buffer> : :<c-x><c-o>`). That might be a bit annoying though, because it would pop up the omnicompletion menu even if you write a `:` inside a comment.
