### ISSUE TITLE
No autocomplete suggestions for cowboy

### ISSUE THREAD

**Issue by t0il3ts0ap** [vim-erlang/vim-erlang-omnicomplete#7]
I am trying the basic cowboy tutorial.
http://ninenines.eu/docs/en/cowboy/1.0/guide/getting_started/

Other relevant plugin installed is 'YouCompleteMe' (In case if anyone is aware of known conflicts)

Though the autocomplete is working for default erlang library, its not working for cowboy.

It says in Omni completion Pattern not found.

By the way,  I am using erlang.mk

Edit:
I made a new project with rebar3. To my surprise, I did not get any results there as well. Has anyone else had issues with rebar3 ?

**Comment by hcs42** [comment]
Besides the built-in modules, currently only rebar2 is supported. (See [this paragraph](https://github.com/vim-erlang/vim-erlang-omnicomplete/blob/8bba501dd117d7324f5f3daf06aaebec0f6e5dcc/doc/vim-erlang-omnicomplete.txt#L53), although I admit it's not too explicit.)

We recently added rebar3 support to the twin project called [vim-erlang-compiler](https://github.com/vim-erlang/vim-erlang-compiler). We should implement rebar3 support the same way here.

A little background: this plugin needs to find where your modules are. In case of rebar2, it reads the rebar.config file to figure out that directories that contain the Erlang modules of your project. In rebar3, that is done differently, and in case of Erlang.mk, it's different again.

**Comment by t0il3ts0ap** [comment]
If no one is planning to work on erlang.mk autocompletion, I would like to contribute for it in future.  Any tips would be of great help.

**Comment by hcs42** [comment]
I don't know about anyone planning to add erlang.mk support, so your contribution would be very welcome.

A few tips:

1. The project is separated into an Erlang part ([erlang_complete.erl][1]) and a Vim part (the rest). You only need to extend the Erlang part to add erlang.mk support.
2. `erlang_complete.erl` can be called from the command line (actually, this is what the Vim part does), which is a convenient way of developing and initial testing.
3. The vim-erlang-compiler project has an erlang_check.erl Escript which is equivalent to the erlang_complete.erl script here. It is slightly more advanced though, because it also supports rebar3 and has some general Makefile support (vim-erlang-omnicomplete only supports rebar2). I think that the Makefile support won't be much useful for implementing the erlang.mk support, but you can get some inspiration and code about [how to support multiple build systems inside one Vim plugin][2]. Feel free to copy code from vim-erlang-compiler to vim-erlang-omnicomplete.
4. Please add Edoc documentation headers and type specs to the new functions (they help in understanding the code).
5. When you write a commit message, please use the current style. E.g. the headline could be: `(#7) Add Erlang.mk support`

Good luck and feel free to ask questions :)

[2]: https://github.com/vim-erlang/vim-erlang-compiler/blob/7d6d3d681375e86474635a8c3ebba82f146332f8/compiler/erlang_check.erl#L258
[1]: https://github.com/vim-erlang/vim-erlang-omnicomplete/blob/master/autoload/erlang_complete.erl

**Comment by dzimi** [comment]
@sanmiguel : I've promised during euc2016 that I will create an issue about rebar3 dependecy autocomplete, but I think it would be a duplicated issue. If you will have time, please do the same tricks as in vim-erlang-compiler. Regards :)

**Comment by sanmiguel** [comment]
l made a PR: #10 - if anyone feels like testing that branch out please let me know how you get on!

I gave it a whirl over here with some simple rebar3 projects and it seems to work as expected, but I don't believe it's possible to have moved code around and not created bugs. Looking forward to hearing your feedback!

**Comment by hcs42** [comment]
#10 was merged.
